/**
 * Generate a signed Osteoflow license key for a customer.
 *
 * Usage:
 *   node scripts/generate-license.mjs <customer_name> <email> [expires_at]
 *
 * Examples:
 *   node scripts/generate-license.mjs "Jean Dupont" "jean@exemple.fr"
 *   node scripts/generate-license.mjs "Jean Dupont" "jean@exemple.fr" "2026-12-31"
 *
 * Requires: scripts/osteoflow_private.pem (generated by generate-keypair.mjs)
 *
 * The private key can also be provided via the OSTEOFLOW_PRIVATE_KEY env var.
 */

import { createSign } from 'crypto'
import { readFileSync, existsSync } from 'fs'
import { fileURLToPath } from 'url'
import path from 'path'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// ─── Args ─────────────────────────────────────────────────────────────────────
const [, , customerName, customerEmail, expiresAt] = process.argv

if (!customerName || !customerEmail) {
  console.error('Usage: node scripts/generate-license.mjs <customer_name> <email> [expires_at]')
  console.error('Example: node scripts/generate-license.mjs "Jean Dupont" "jean@exemple.fr" "2026-12-31"')
  process.exit(1)
}

if (expiresAt && isNaN(Date.parse(expiresAt))) {
  console.error(`Date d'expiration invalide: ${expiresAt}. Format attendu: YYYY-MM-DD`)
  process.exit(1)
}

// ─── Load private key ─────────────────────────────────────────────────────────
let privateKey
if (process.env.OSTEOFLOW_PRIVATE_KEY) {
  privateKey = process.env.OSTEOFLOW_PRIVATE_KEY
} else {
  const keyPath = path.join(__dirname, 'osteoflow_private.pem')
  if (!existsSync(keyPath)) {
    console.error('Clé privée introuvable. Lancez d\'abord: node scripts/generate-keypair.mjs')
    process.exit(1)
  }
  privateKey = readFileSync(keyPath, 'utf-8')
}

// ─── Build payload ────────────────────────────────────────────────────────────
const payload = {
  customer: customerName.trim(),
  email: customerEmail.trim().toLowerCase(),
  issuedAt: new Date().toISOString().split('T')[0],
  expiresAt: expiresAt ? new Date(expiresAt).toISOString().split('T')[0] : null,
  version: '1',
}

const payloadJson = JSON.stringify(payload)

// ─── Sign ─────────────────────────────────────────────────────────────────────
const sign = createSign('SHA256')
sign.update(payloadJson)
sign.end()
const signature = sign.sign(privateKey, 'base64url')

const payloadB64 = Buffer.from(payloadJson).toString('base64url')
const licenseKey = `${payloadB64}.${signature}`

// ─── Output ───────────────────────────────────────────────────────────────────
console.log('')
console.log('──────────────────────────────────────────────────')
console.log('Licence générée avec succès')
console.log('──────────────────────────────────────────────────')
console.log(`Client   : ${payload.customer}`)
console.log(`Email    : ${payload.email}`)
console.log(`Émise le : ${payload.issuedAt}`)
console.log(`Expire   : ${payload.expiresAt ?? 'Jamais (licence perpétuelle)'}`)
console.log('')
console.log('Clé de licence (à envoyer au client):')
console.log('──────────────────────────────────────────────────')
console.log(licenseKey)
console.log('──────────────────────────────────────────────────')
console.log('')
